In [1]:
# numpy- short for numerical python
# its a pytho lib and used for working with arrays, its an open source project
# it has functions for working in domains of linear algebra, fourier transform, and matrices
# list are slow to process so we use arrays which are 50x faster - ndarray

In [2]:
# example:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 0D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [5]:
# 1D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
# 2D arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3D array with 2 2D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# mix
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
# example?
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[2]+arr[3])

1
7


In [16]:
# access 2d arrays
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row: ", arr[0,1])

2nd element on 1st row:  2


In [18]:
# slicing operation
# it means taking elements from one index to another, we pass it like [start:end]
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1:3])
# where start index hasnt been specified we consider it as 0

[2 3]


In [20]:
# negative slicing
import numpy as np
arr = np.array([1,2,3,4])
print(arr[-3:-1])

[2 3]


In [22]:
# step value
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:3:2])

[2]
