In [1]:
# slicing of 2d array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [5]:
# question 1
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
element = arr[1,2] #selects the element at row index 1, column index 2
print(element)

6


In [8]:
# question 2
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice = arr[0:2,] #selects rows with index 0 and 1, all columns
print(row_slice)

[[1 2 3]
 [4 5 6]]


In [9]:
# question 3
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice = arr[:,1:3] #select all rows, columns with index 1 and 3
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
